version: "2"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    networks:
      test:
        aliases: ['db.local']
    environment:
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitter
      MYSQL_DATABASE: twitter
      MYSQL_ROOT_PASSWORD: twitter
    ports:
      - 3306:3306


networks:
  test: {}
